drop table IsQualifiledIn;
drop table Reservation; 
drop table Hosted; 
drop table Equipment;
drop table Class;
drop table Instructor;
drop table FitnessMeasurement;
drop table GymMember;
drop table GymBranch;
drop table ClassType;
drop table TimePeriod;
drop table Customer;
commit;