drop table FitnessMeasurement;
drop table GymMember; 
drop table Customer; 
drop table Instructor;
drop table Class;
drop table TimePeriod;
drop table ClassType;
drop table Equipment;
drop table Hosted;
drop table Reservation;
drop table IsQualifiledIn;
commit;